name: Build Backend

on:
  push:
    branches:
      - merged
  pull_request:
    branches:
      - merged

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore NuGet packages
        run: dotnet restore backend

      - name: Build project
        run: dotnet build --configuration Release backend
